### ISSUE TITLE
[props-order]: Reconsider props order rule

### ISSUE THREAD

**Issue by Monchi** [Monchi/eslint-plugin-chakra-ui#15]
from https://github.com/Monchi/eslint-plugin-chakra-ui/pull/13#pullrequestreview-866960683

**Comment by no-yan** [comment]
## order in same priority
I don't have any opinions about the same priorities.

## order of priorities
I feel that it is better to create several groups, such as Positioning, Box Model, Typography and so on.

My plan was this.
https://github.com/no-yan/eslint-plugin-chakraui/blob/6661b203ec762eb85021794eb0b29c6abbc1b09f/src/utils/getPriority.ts#L311-L339

ref: https://github.com/constverum/stylelint-config-rational-order#stylelint-config-rational-order

**Comment by no-yan** [comment]
I'm looking [A few ordering plugins of Stylelint](https://qiita.com/nabepon/items/4168eae542861cfd69f7).

**Comment by Monchi** [comment]
@no-yan 
It sounds good to take over the grouping logic from stylelint. Current grouping logic just follows [the doc](https://chakra-ui.com/docs/features/style-props).

So the priority will be like below?

1. Reserved first
2. Component-specific props
3. Style props
    - Positioning
    - Box Model
    - etc...
4. other props
5. Reserved last

Component-specific props and style props should be reversible via option.

**Comment by no-yan** [comment]
@Monchi 
Yes! 
If it looks OK, I'll try to make something that actually works.
Actually using it can make us aware where to improve, I think.

**Comment by Monchi** [comment]
@no-yan This have solved by #21, right?

**Comment by no-yan** [comment]
I agree.  It looks okay so I'll close it.

If there is any feedback, please reopen it. Otherwise, open a new issue.
