### ISSUE TITLE
chakra-ui/require-specific-component error

### ISSUE THREAD

**Issue by mikecx** [Monchi/eslint-plugin-chakra-ui#32]
When enabling the `chakra-ui/require-specific-component` rule, I get `1:1  error  Definition for rule 'chakra-ui/require-specific-component' was not found`

I'm using the latest eslint-plugin-chakra-ui, 0.60 and the other rules seem to work just fine. I'm up to date on all my other dev dependencies as well.

Looks like it's missing from the export here:
https://github.com/Monchi/eslint-plugin-chakra-ui/blob/master/src/index.ts

**Comment by Monchi** [comment]
@mikecx Thank you for reporting! I've released the fix #33 with v0.6.1. Please try it.
